version: '3.7'

services:
  mysql:
    image: wcr.baemin.in/mysql/mysql-server:5.7
    container_name: meeting-mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/0_init.sql
